repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.26
  hooks:
    - id: tflint
      args:
        # - "--module"
        # - "--deep"
        - "--config=.tflint.hcl"
    - id: terraform-validate
    - id: terraform-fmt
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.3
  hooks:
    - id: terraform_trivy
    - id: terraform_docs
    - id: checkov